import { Router } from 'express';
import authRoutes from './auth.routes';
import testRoutes from './test.routes';
import packageRoutes from './package.routes';
import bookingRoutes from './booking.routes';
import patientRoutes from './patient.routes';
import doctorRoutes from './doctor.routes';
import branchRoutes from './branch.routes';
import contactRoutes from './contact.routes';
import blogRoutes from './blog.routes';
import uploadRoutes from './upload.routes';
import testimonialRoutes from './testimonial.routes';
import paymentRoutes from './payment.routes';
import reportRoutes from './report.routes';
import invoiceRoutes from './invoice.routes';
import reportsRoutes from './reports.routes';
import adminRoutes from './admin.routes';
import labRoutes from './lab.routes';
import doctorPortalRoutes from './doctor.routes';
import inventoryRoutes from './inventory.routes';
import supplierRoutes from './supplier.routes';
import purchaseOrderRoutes from './purchase-order.routes';
import crmRoutes from './crm.routes';
import employeeRoutes from './employee.routes';
import accountingRoutes from './accounting.routes';

const apiRouter = Router();

apiRouter.use('/auth', authRoutes);
apiRouter.use('/tests', testRoutes);
apiRouter.use('/packages', packageRoutes);
apiRouter.use('/bookings', bookingRoutes);
apiRouter.use('/patients', patientRoutes);
apiRouter.use('/doctors', doctorRoutes);
apiRouter.use('/branches', branchRoutes);
apiRouter.use('/contact', contactRoutes);
apiRouter.use('/blogs', blogRoutes);
apiRouter.use('/uploads', uploadRoutes);
apiRouter.use('/testimonials', testimonialRoutes);
apiRouter.use('/payments', paymentRoutes);
apiRouter.use('/reports', reportRoutes);
apiRouter.use('/reports/download', reportsRoutes);
apiRouter.use('/invoices/download', reportsRoutes);
apiRouter.use('/admin', adminRoutes);
apiRouter.use('/lab', labRoutes);
apiRouter.use('/doctor', doctorPortalRoutes);
apiRouter.use('/invoices', invoiceRoutes);
apiRouter.use('/inventory', inventoryRoutes);
apiRouter.use('/suppliers', supplierRoutes);
apiRouter.use('/purchase-orders', purchaseOrderRoutes);
apiRouter.use('/crm', crmRoutes);
apiRouter.use('/employees', employeeRoutes);
apiRouter.use('/accounting', accountingRoutes);

export { apiRouter };
